config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'results#home'
   
   resources :subjects
   
   resources :results do
     collection do
       get 'student_login'
       get 'teacher_login'
       get 'headmaster_login'
       get 'student_addmission'
       post 'student_create'
     end
     
     member do
       get 'student_edit'
       post 'student_update'
     end
   end

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id, :scope => :sname
  validates_numericality_of :marks, :only_integer => true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  validates :sname, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :results
  accepts_nested_attributes_for :results
  validates_inclusion_of :gender, :in => %w( m f M F)
  validates :rollnumber, uniqueness: true, :allow_blank => true, :allow_nil => true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  enum role: {"student"=>0, "teacher"=>1, "head_master"=>2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

    protected

    def configure_devise_permitted_parameters
      registration_params = [:email, :password, :password_confirmation, :name, :phone, :gender, :rollnumber]

      if params[:action] == 'update'
        devise_parameter_sanitizer.for(:account_update) { 
          |u| u.permit(registration_params << :current_password)
        }
      elsif params[:action] == 'create'
        devise_parameter_sanitizer.for(:sign_up) { 
          |u| u.permit(registration_params) 
        }
      end
    end
    
    def after_sign_in_path_for(resource)
      if current_user.role == 'student'
        student_login_results_path
      elsif current_user.role == 'teacher'
        teacher_login_results_path
      else
        headmaster_login_results_path
      end
    end
    
    def check_student_privileges!
      if current_user
        redirect_to student_login_results_path, notice: 'You dont have enough permissions to be there' unless current_user.role == 'teacher' || current_user.role == 'head_master'
      else
        redirect_to user_session_path
      end
    end
    
    def check_teacher_privileges!
      if current_user
        redirect_to headmaster_login_results_path, notice: 'Only Teacher can add Marks' unless current_user.role == 'teacher'
      else
        redirect_to user_session_path
      end
    end
    
    def check_hm_privileges!
      if current_user
        redirect_to student_login_results_path, notice: 'Only Head Master can add Student' if current_user.role == 'student'
        redirect_to teacher_login_results_path, notice: 'Only Head Master can add Student' if current_user.role == 'teacher'
      else
        redirect_to user_session_path
      end
    end
    
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_filter :check_student_privileges!, except: :student_login
  before_filter :check_teacher_privileges!, only: :new
  before_filter :check_hm_privileges!, only: [:headmaster_login, :student_addmission, :student_edit]
  
  def new
    @result = Result.new
    @subjects = Subject.all
    @users = User.where(:role => 0)
  end
  
  def create
    @subjects = Subject.all
    @users = User.where(:role => 0)
    @result = Result.new(subject_params)
    if @result.save
      redirect_to results_path, notice: 'Result Saved'
    else
      flash[:notice] = "Result Not saved"
      redirect_to :back
    end
  end
  
  def index
    @result = Result.all
  end
  
  def home
    if current_user
      if current_user.role == 'student'
        redirect_to student_login_results_path
      elsif current_user.role == 'teacher'
        redirect_to teacher_login_results_path
      else
        redirect_to headmaster_login_results_path
      end
    else
      redirect_to user_session_path
    end
  end
  
  def student_login
    @result = current_user.results
    @student = current_user
    if current_user.gender == 'm' || current_user.gender == 'M'
      @name = ' Mr. ' + current_user.name
    elsif
      @name = ' Miss. ' + current_user.name
    end
  end
  
  def teacher_login
    @students = User.where(:role => 0)
    @number_of_students = @students.count
    if current_user.gender == 'm' || current_user.gender == 'M'
      @name = ' Mr. ' + current_user.name
    else
      @name = ' Miss. ' + current_user.name
    end
  end
  
  def headmaster_login
    @students = User.where(:role => 0)
    @number_of_students = @students.count
    if current_user.gender == 'm' || current_user.gender == 'M'
      @name = ' Mr. ' + current_user.name
    else
      @name = ' Miss. ' + current_user.name
    end
  end
  
  def student_addmission
    @student = User.new
  end
  
  def student_edit
    @student = User.find(params[:id])
  end
  
  def student_create
    @student = User.new(params.require(:student).permit(:id, :email, :rollnumber, :password, 
                                                        :password_confirmation, :name, :phone, :gender))
    @student.save
    redirect_to headmaster_login_results_path
  end
  
  def student_update
    @student = User.find(params[:id])
 
    if @student.update(params.require(:student).permit(:id, :email, :rollnumber, :password, 
                                                        :password_confirmation, :name, :phone, :gender))
      redirect_to headmaster_login_results_path
    else
      render 'student_edit'
    end
  end
  
  private
    def subject_params
      params.require(:result).permit(:user_id, :sname, :marks)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :check_student_privileges!
  
  def index
    @subject = Subject.all
  end
  
  def new
    @subject = Subject.new
  end
  
  def edit
    @subject = Subject.find(params[:id])
  end
  
  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to subjects_path
    else
      render 'new'
    end
  end
  
  def update
    @subject = Subject.find(params[:id])
 
    if @subject.update(subject_params)
      redirect_to subjects_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
 
    redirect_to subjects_path
  end
  
private
  def subject_params
    params.require(:subject).permit(:sname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style='background-color: #F5F7FF'>
	<div class="container" style="background-color:white">
		<div class='navbar'>
		<% if notice %>
  	  		<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
  	  		<p class="alert alert-danger"><%= alert %></p>
		<% end %>
		
		
		<% if user_signed_in? %>
			<%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'loginlogout') %>
		<% else %>
			<h1 class="text-center">Please Login to Continue</h1>
			<%= link_to('Login', new_user_session_path, :class => 'loginlogout')  %>
		<% end %>
		
		<%= yield %>
	</div>
	</div>
</body>
</html>

app/views/results/_form.html.erb
 
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Student_Email %><br />
    <%= f.email_field :email %>
  </p>
  
  <p>
    <%= f.label :Roll_Number %><br />
    <%= f.text_field :rollnumber %>
  </p>
  
  <p>
    <%= f.label :Password %><br />
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.label :Confirm_Password %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  
  <p>
    <%= f.label :Name %><br />
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :Phone %><br />
    <%= f.text_field :phone %>
  </p>
  
  <p>
    <%= f.label :Gender %><br />
	<%= f.radio_button :gender, 'M' %> Male
	<%= f.radio_button :gender, 'F' %> Female
  </p>
  
  <p>
    <%= f.submit %>
  </p>

app/views/results/headmaster_login.html.erb
<h1 class="text-center"> Welcome <%= @name %></h1>
<%if @number_of_students >= 1%>
	<h1>List of Students</h1>
	<table class='table'>
  	  <tr>
		  <th>Student Name</th>
		  <th>Roll Number</th>
		  <th>Phone</th>
		  <th>Gender</th>
		  <th>Email</th>
		  <th></th>
	  </tr>
	  <% @students.each do |student| %>
	  <tr>
      	<td><%= student.name %></td>
	  	<td><%= student.rollnumber %></td>
	  	<td><%= student.phone %></td>
	  	<td><%= student.gender %></td>
	  	<td><%= student.email %></td>
	  	<td><%= link_to 'Edit', student_edit_result_path(student), :class => 'btn btn-default' %></td>
	  </tr>
	  <% end %>
	</table>
<%end%>
<p><%= link_to('Add a New Student', student_addmission_results_path, :class => 'btn btn-info') %> </p>
<p><%= link_to('Add a New Subject', new_subject_path, :class => 'btn btn-info') %> </p>
<p><%= link_to('Students Result', results_path, :class => 'btn btn-info') %> </p>

app/views/results/index.html.erb
<h1>Listing Result</h1>
<table class='table'>
  <tr>
    <th>Student Roll Number</th>
	<th>Subject</th>
	<th>Marks</th>
  </tr>
 
  <% @result.each do |result| %>
    <tr>
      <td><%= result.user.rollnumber %></td>
	  <td><%= result.sname %></td>
	  <td><%= result.marks %></td>
    </tr>
  <% end %>
</table>
<%if current_user %>
	<% if current_user.role == 'teacher'%>
		<p><%= link_to 'New Result', new_result_path, :class => 'btn btn-info' %></p>
		<p><%= link_to('My Home', teacher_login_results_path, :class => 'btn btn-info')  %></p>
	<%elsif current_user.role == 'head_master'%>
    	<p><%= link_to('My Home', headmaster_login_results_path, :class => 'btn btn-info')  %></p>
	<%end%>
<%end%>

app/views/results/new.html.erb
<%= form_for @result do |f| %>
 
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @result.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Student_RollNumber %>
	<% options = options_from_collection_for_select(@users, 'id', 'rollnumber') %>
	<%= f.select :user_id,  options %>
  </p>
   
  <p>
    <%= f.label :Subject %>
	<% options = options_from_collection_for_select(@subjects, 'sname', 'sname') %>
	<%= f.select :sname,  options %>
  </p>
  
  <p>
    <%= f.label :marks %>
    <%= f.text_field :marks %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  <p><%= link_to('All Results', results_path, :class => 'btn btn-info')  %></p>
  <%if current_user %>
  	<% if current_user.role == 'teacher'%>
  		<p><%= link_to('My Home', teacher_login_results_path, :class => 'btn btn-info')  %></p>
 	<%elsif current_user.role == 'head_master'%>
  		<p><%= link_to('My Home', headmaster_login_results_path, :class => 'btn btn-info')  %></p>
  	<%end%>
  <%end%>
<% end %>

app/views/results/student_addmission.html.erb
<h1>New Student</h1>
<%= form_for :student, url: student_create_results_path do |f| %>
<%= render 'form', f: f %>
<% end %>
<%= link_to 'All Students', headmaster_login_results_path, :class => 'btn btn-info' %>

app/views/results/student_edit.html.erb
<h1>Edit Student</h1>
<%= form_for :student, url: student_update_result_path do |f| %>
<%= render 'form', f: f %>
<% end %>
<%= link_to 'All Students', headmaster_login_results_path %>

app/views/results/student_login.html.erb
<h1 class="text-center"> Welcome <%= @name %></h1>
<table class='table table-bordered'>
	<tr>
		<th>Student Name</th>
		<td><%= @student.name%></td>
	</tr>
	<tr>
		<th>Roll Number</th>
		<td><%= @student.rollnumber%></td>
	</tr>
	<tr>
		<th>Email ID</th>
		<td><%= @student.email%></td>
	</tr>
	<tr>
		<th>Phone</th>
		<td><%= @student.phone%></td>
	</tr>
</table>

<table class='table'>
  <tr>
    <th>Subject</th>
	<th>Marks</th>
	<th>Result</th>
  </tr>
 
  <% @result.each do |result| %>
    <tr>
	  <td><%= result.sname %></td>
	  <td><%= result.marks %></td>
	  <td>
	  	<% if result.marks >= 70 %>
			<%= 'Distinction' %>
		<% elsif result.marks >= 60 and result.marks < 70 %>
			<%= 'First Class' %>
		<% elsif result.marks >= 50 and result.marks < 60 %>
			<%= 'Second Class' %>
		<% elsif result.marks >= 40 and result.marks < 50 %>
			<%= 'Third Class' %>
		<% else %>
			<%= 'Fail' %>
		<% end %>
	  </td>
    </tr>
  <% end %>
</table>

app/views/results/teacher_login.html.erb
<h1 class="text-center">Welcome<%= @name %></h1>
<%if @number_of_students >= 1%>
	<h1>List of Students</h1>
	<table class='table'>
  	  <tr>
		  <th>Student Name</th>
		  <th>Roll Number</th>
		  <th>Phone</th>
		  <th>Gender</th>
		  <th>Email</th>
	  </tr>
	  <% @students.each do |student| %>
	  <tr>
      	<td><%= student.name %></td>
	  	<td><%= student.rollnumber %></td>
	  	<td><%= student.phone %></td>
	  	<td><%= student.gender %></td>
	  	<td><%= student.email %></td>
	  </tr>
	  <% end %>
	</table>
<%end%>
<p><%= link_to('Add a Subject', new_subject_path, :class => 'btn btn-info') %> </p>
<p><%= link_to('Add the Result', new_result_path, :class => 'btn btn-info') %> </p>

app/views/subjects/_form.html.erb
<%= form_for @subject do |f| %>
 
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@subject.errors.count, "error") %> prohibited
        this Subject from being saved:
      </h2>
      <ul>
        <% @subject.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :sname %>
    <%= f.text_field :sname %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>
<%= render 'form' %>
 
<%= link_to 'Back', subjects_path, :class => 'btn btn-info' %>

app/views/subjects/index.html.erb
<h1>Listing Subjects</h1>
<table class='table'>
  <tr>
    <th>Subject Name</th>
    <th colspan="2"></th>
  </tr>
 
  <% @subject.each do |subject| %>
    <tr>
      <td><%= subject.sname %></td>
      <td><%= link_to 'Edit', edit_subject_path(subject), :class => 'btn btn-default' %></td>
	  <td><%= link_to 'Delete', subject_path(subject),
	                method: :delete,
	                data: { confirm: 'Are you sure?' }, :class => 'btn btn-default' %></td>
    </tr>
  <% end %>
</table>
<p><%= link_to 'New Subject', new_subject_path, :class => 'btn btn-info' %></p>
<%if current_user %>
	<% if current_user.role == 'teacher'%>
		<p><%= link_to('My Home', teacher_login_results_path, :class => 'btn btn-info')  %></p>
	<%elsif current_user.role == 'head_master'%>
		<p><%= link_to('My Home', headmaster_login_results_path, :class => 'btn btn-info')  %></p>
	<%end%>
<%end%>

app/views/subjects/new.html.erb
<h1>New SUBJECT</h1>
<%= render 'form' %>
<p><%= link_to 'All Subjects', subjects_path, :class => 'btn btn-info' %></p>
<%if current_user %>
	<% if current_user.role == 'teacher'%>
		<p><%= link_to('My Home', teacher_login_results_path, :class => 'btn btn-info')  %></p>
	<%elsif current_user.role == 'head_master'%>
		<p><%= link_to('My Home', headmaster_login_results_path, :class => 'btn btn-info')  %></p>
	<%end%>
<%end%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>